"""
Mock veri: FortiManager (3 ADOM) + Palo Alto (3 VSYS)
Gerçek API yanıtlarını simüle eder.
"""

FORTIMANAGER_MOCK = {
    "host": "192.168.1.100",
    "version": "7.4.2",
    "adoms": [
        # ── ADOM 1: BankingCorp ──────────────────────────────────
        {
            "name": "ADOM_BankingCorp",
            "customer": "BankingCorp A.Ş.",
            "policies": [
                {
                    "policyid": 1,
                    "name": "Legacy-Internet-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["all"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "Eski kural - kaldırılacak",
                },
                {
                    "policyid": 2,
                    "name": "SSH-Management-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["Management-Servers"],
                    "service": ["SSH"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 3,
                    "name": "RDP-Remote-Support",
                    "srcaddr": ["all"],
                    "dstaddr": ["IT-Workstations"],
                    "service": ["RDP"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Teknik destek erişimi",
                },
                {
                    "policyid": 4,
                    "name": "FTP-Backup-Transfer",
                    "srcaddr": ["all"],
                    "dstaddr": ["Backup-Servers"],
                    "service": ["FTP"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 5,
                    "name": "Internal-DMZ-Access",
                    "srcaddr": ["10.0.0.0/8"],
                    "dstaddr": ["DMZ-Servers"],
                    "service": ["HTTP", "HTTPS", "DNS"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "İç ağ DMZ erişimi",
                },
                {
                    "policyid": 6,
                    "name": "HTTP-Web-Frontend",
                    "srcaddr": ["all"],
                    "dstaddr": ["Web-Frontend"],
                    "service": ["HTTP"],
                    "action": "accept",
                    "logtraffic": "utm",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 7,
                    "name": "Block-P2P-Traffic",
                    "srcaddr": ["all"],
                    "dstaddr": ["all"],
                    "service": ["BITTORRENT", "GNUTELLA"],
                    "action": "deny",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "P2P engelleme",
                },
                {
                    "policyid": 8,
                    "name": "Old-IPSEC-VPN-2021",
                    "srcaddr": ["10.20.0.0/24"],
                    "dstaddr": ["10.30.0.0/24"],
                    "service": ["IKE", "IPSEC"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "disable",
                    "comments": "2021 yılı VPN tüneli - kullanım dışı",
                },
                {
                    "policyid": 9,
                    "name": "SNMP-Network-Monitoring",
                    "srcaddr": ["10.10.0.0/16"],
                    "dstaddr": ["all"],
                    "service": ["SNMP"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "Ağ izleme sistemi",
                },
                {
                    "policyid": 10,
                    "name": "Outbound-Mail",
                    "srcaddr": ["Mail-Servers"],
                    "dstaddr": ["all"],
                    "service": ["SMTP", "SMTPS"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Mail çıkış trafiği",
                },
            ],
        },

        # ── ADOM 2: RetailChain ──────────────────────────────────
        {
            "name": "ADOM_RetailChain",
            "customer": "RetailChain Mağazacılık",
            "policies": [
                {
                    "policyid": 1,
                    "name": "POS-Internet-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["all"],
                    "service": ["HTTP", "HTTPS"],
                    "action": "accept",
                    "logtraffic": "utm",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 2,
                    "name": "RDP-Store-Management",
                    "srcaddr": ["all"],
                    "dstaddr": ["Store-Servers"],
                    "service": ["RDP"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Mağaza yönetim erişimi",
                },
                {
                    "policyid": 3,
                    "name": "DB-External-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["DB-Servers"],
                    "service": ["MYSQL"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 4,
                    "name": "Internal-LAN",
                    "srcaddr": ["192.168.0.0/16"],
                    "dstaddr": ["192.168.0.0/16"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "İç LAN trafiği",
                },
                {
                    "policyid": 5,
                    "name": "Backup-FTP-Nightly",
                    "srcaddr": ["10.0.1.0/24"],
                    "dstaddr": ["Backup-Host"],
                    "service": ["FTP"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 6,
                    "name": "Guest-Wifi-HTTP",
                    "srcaddr": ["192.168.100.0/24"],
                    "dstaddr": ["all"],
                    "service": ["HTTP", "HTTPS"],
                    "action": "accept",
                    "logtraffic": "utm",
                    "status": "enable",
                    "comments": "Misafir WiFi internet erişimi",
                },
                {
                    "policyid": 7,
                    "name": "Old-Telnet-Rule",
                    "srcaddr": ["10.0.0.0/8"],
                    "dstaddr": ["Network-Devices"],
                    "service": ["TELNET"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Eski cihaz yönetim - yeni switch'lerde SSH kullanılıyor",
                },
                {
                    "policyid": 8,
                    "name": "Deactivated-Partner-VPN",
                    "srcaddr": ["10.50.0.0/24"],
                    "dstaddr": ["10.60.0.0/24"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "disable",
                    "comments": "Partner entegrasyonu sona erdi",
                },
            ],
        },

        # ── ADOM 3: HealthSector ─────────────────────────────────
        {
            "name": "ADOM_HealthSector",
            "customer": "HealthSector Sağlık Grubu",
            "policies": [
                {
                    "policyid": 1,
                    "name": "Emergency-Any-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["all"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 2,
                    "name": "PACS-Server-SSH",
                    "srcaddr": ["all"],
                    "dstaddr": ["PACS-Servers"],
                    "service": ["SSH"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "PACS yönetimi",
                },
                {
                    "policyid": 3,
                    "name": "HIS-Database",
                    "srcaddr": ["all"],
                    "dstaddr": ["HIS-DB"],
                    "service": ["MSSQL"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 4,
                    "name": "Doctor-RDP-Access",
                    "srcaddr": ["all"],
                    "dstaddr": ["Clinical-Workstations"],
                    "service": ["RDP"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Doktor uzaktan erişim",
                },
                {
                    "policyid": 5,
                    "name": "Patient-Portal-HTTP",
                    "srcaddr": ["all"],
                    "dstaddr": ["Patient-Portal"],
                    "service": ["HTTP", "HTTPS"],
                    "action": "accept",
                    "logtraffic": "utm",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 6,
                    "name": "Internal-Mednet",
                    "srcaddr": ["172.16.0.0/12"],
                    "dstaddr": ["172.16.0.0/12"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "Medikal ağ iç trafiği",
                },
                {
                    "policyid": 7,
                    "name": "Legacy-Telnet-BedSide",
                    "srcaddr": ["10.0.0.0/8"],
                    "dstaddr": ["BedSide-Terminals"],
                    "service": ["TELNET"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Eski yatak başı terminal",
                },
                {
                    "policyid": 8,
                    "name": "Lab-FTP-Results",
                    "srcaddr": ["all"],
                    "dstaddr": ["Lab-Servers"],
                    "service": ["FTP"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "",
                },
                {
                    "policyid": 9,
                    "name": "Deny-Social-Media",
                    "srcaddr": ["all"],
                    "dstaddr": ["all"],
                    "service": ["YOUTUBE", "FACEBOOK", "TWITTER"],
                    "action": "deny",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Sosyal medya engel",
                },
                {
                    "policyid": 10,
                    "name": "Old-Radiology-VPN",
                    "srcaddr": ["10.99.0.0/24"],
                    "dstaddr": ["10.88.0.0/24"],
                    "service": ["ALL"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "disable",
                    "comments": "Radyoloji şubesi VPN - kapatıldı",
                },
                {
                    "policyid": 11,
                    "name": "NTP-Sync",
                    "srcaddr": ["Servers"],
                    "dstaddr": ["NTP-Pool"],
                    "service": ["NTP"],
                    "action": "accept",
                    "logtraffic": "all",
                    "status": "enable",
                    "comments": "Sunucu zaman senkronizasyonu",
                },
                {
                    "policyid": 12,
                    "name": "Admin-SNMP",
                    "srcaddr": ["10.0.0.0/8"],
                    "dstaddr": ["all"],
                    "service": ["SNMP"],
                    "action": "accept",
                    "logtraffic": "disable",
                    "status": "enable",
                    "comments": "",
                },
            ],
        },
    ],
}


PALOALTO_MOCK = {
    "host": "192.168.1.200",
    "version": "11.1.2",
    "vsys_list": [
        # ── VSYS 1: TechStartup ──────────────────────────────────
        {
            "name": "vsys1_TechStartup",
            "customer": "TechStartup Yazılım",
            "rules": [
                {
                    "name": "dev-full-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["trust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "ssh-jumpbox-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["dmz"],
                    "source": ["any"],
                    "destination": ["jumpbox"],
                    "application": ["ssh"],
                    "service": ["service-ssh"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "web-server-http",
                    "from_zones": ["untrust"],
                    "to_zones": ["dmz"],
                    "source": ["any"],
                    "destination": ["web-servers"],
                    "application": ["web-browsing", "ssl"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "internal-to-internet",
                    "from_zones": ["trust"],
                    "to_zones": ["untrust"],
                    "source": ["10.0.0.0/8"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "İç ağ internet çıkışı",
                },
                {
                    "name": "old-test-rule",
                    "from_zones": ["trust"],
                    "to_zones": ["dmz"],
                    "source": ["test-subnet"],
                    "destination": ["dev-servers"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": True,
                    "description": "Test ortamı - kullanım dışı",
                },
                {
                    "name": "ci-cd-pipeline",
                    "from_zones": ["trust"],
                    "to_zones": ["dmz"],
                    "source": ["ci-servers"],
                    "destination": ["artifact-registry"],
                    "application": ["git", "http", "ssl"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "CI/CD pipeline erişimi",
                },
                {
                    "name": "block-torrents",
                    "from_zones": ["trust"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["bittorrent"],
                    "service": ["any"],
                    "action": "deny",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "P2P engelleme",
                },
                {
                    "name": "monitoring-snmp",
                    "from_zones": ["mgmt"],
                    "to_zones": ["trust"],
                    "source": ["monitoring-server"],
                    "destination": ["any"],
                    "application": ["snmp"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Ağ izleme",
                },
                {
                    "name": "rdp-dev-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["trust"],
                    "source": ["any"],
                    "destination": ["dev-workstations"],
                    "application": ["msrdp"],
                    "service": ["service-rdp"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "",
                },
            ],
        },

        # ── VSYS 2: Logistics ────────────────────────────────────
        {
            "name": "vsys2_Logistics",
            "customer": "Logistics Global Lojistik",
            "rules": [
                {
                    "name": "warehouse-any-out",
                    "from_zones": ["warehouse"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "erp-db-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["db"],
                    "source": ["any"],
                    "destination": ["erp-db"],
                    "application": ["oracle-db"],
                    "service": ["tcp-1521"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "ERP veritabanı erişimi",
                },
                {
                    "name": "tracking-portal",
                    "from_zones": ["untrust"],
                    "to_zones": ["dmz"],
                    "source": ["any"],
                    "destination": ["tracking-server"],
                    "application": ["web-browsing", "ssl"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Gönderi takip portalı",
                },
                {
                    "name": "ssh-fleet-management",
                    "from_zones": ["untrust"],
                    "to_zones": ["trust"],
                    "source": ["any"],
                    "destination": ["fleet-servers"],
                    "application": ["ssh"],
                    "service": ["service-ssh"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "old-partner-api",
                    "from_zones": ["untrust"],
                    "to_zones": ["trust"],
                    "source": ["partner-ips"],
                    "destination": ["api-servers"],
                    "application": ["http", "ssl"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": True,
                    "description": "Eski partner API entegrasyonu",
                },
                {
                    "name": "telnet-legacy-scanner",
                    "from_zones": ["warehouse"],
                    "to_zones": ["trust"],
                    "source": ["scanner-devices"],
                    "destination": ["inventory-server"],
                    "application": ["telnet"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Depo el terminalleri",
                },
                {
                    "name": "deny-all-out",
                    "from_zones": ["any"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "deny",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Default deny",
                },
            ],
        },

        # ── VSYS 3: Education ────────────────────────────────────
        {
            "name": "vsys3_Education",
            "customer": "EduNet Eğitim Kurumları",
            "rules": [
                {
                    "name": "student-internet",
                    "from_zones": ["student-net"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "admin-ssh-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["server-farm"],
                    "source": ["any"],
                    "destination": ["admin-servers"],
                    "application": ["ssh"],
                    "service": ["service-ssh"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Sistem yönetici SSH",
                },
                {
                    "name": "lms-access",
                    "from_zones": ["untrust"],
                    "to_zones": ["dmz"],
                    "source": ["any"],
                    "destination": ["lms-server"],
                    "application": ["web-browsing", "ssl"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "LMS öğrenci erişimi",
                },
                {
                    "name": "staff-rdp",
                    "from_zones": ["untrust"],
                    "to_zones": ["trust"],
                    "source": ["any"],
                    "destination": ["staff-pcs"],
                    "application": ["msrdp"],
                    "service": ["service-rdp"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Personel uzak masaüstü",
                },
                {
                    "name": "library-db",
                    "from_zones": ["library"],
                    "to_zones": ["trust"],
                    "source": ["library-pcs"],
                    "destination": ["library-db"],
                    "application": ["mysql"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": False,
                    "description": "Kütüphane veritabanı",
                },
                {
                    "name": "old-vclass-system",
                    "from_zones": ["trust"],
                    "to_zones": ["dmz"],
                    "source": ["teacher-pcs"],
                    "destination": ["old-vclass"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": True,
                    "description": "Eski sanal sınıf - Teams'e geçildi",
                },
                {
                    "name": "mail-server",
                    "from_zones": ["trust"],
                    "to_zones": ["untrust"],
                    "source": ["mail-server"],
                    "destination": ["any"],
                    "application": ["smtp", "imap", "pop3"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Mail sunucu çıkışı",
                },
                {
                    "name": "guest-wifi-open",
                    "from_zones": ["guest"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["any"],
                    "service": ["any"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": False,
                    "disabled": False,
                    "description": "",
                },
                {
                    "name": "block-gaming",
                    "from_zones": ["student-net"],
                    "to_zones": ["untrust"],
                    "source": ["any"],
                    "destination": ["any"],
                    "application": ["gaming"],
                    "service": ["any"],
                    "action": "deny",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "Oyun trafiği engel",
                },
                {
                    "name": "ntp-time-sync",
                    "from_zones": ["trust"],
                    "to_zones": ["untrust"],
                    "source": ["servers"],
                    "destination": ["ntp-servers"],
                    "application": ["ntp"],
                    "service": ["application-default"],
                    "action": "allow",
                    "log_start": False,
                    "log_end": True,
                    "disabled": False,
                    "description": "NTP senkronizasyonu",
                },
            ],
        },
    ],
}
